"""Generate src/zapf.rs: ZapfDingbats glyph names to codepoints.

A Dingbats font names its glyphs `a1` through `a191`, and those names are not
in the Adobe Glyph List proper -- they have their own list. Without it a
Type 1 Dingbats font scans as covering two characters, space and nbspace,
and no symbol lookup will ever reach it.

Run from the repo root:  python tools/gen_zapf.py
(after fetching scripts/zapfdingbats.txt from adobe-type-tools/agl-aglfn)
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from emit import emit  # noqa: E402

SRC = 'scripts/zapfdingbats.txt'
OUT = 'src/zapf.rs'

table = []
with io.open(SRC, encoding='utf-8') as f:
    for line in f:
        line = line.split('#')[0].strip()
        if not line:
            continue
        name, code = line.split(';')[:2]
        table.append((name.strip(), int(code, 16)))

# A name can appear more than once; the first wins, matching a linear search
# over the file as written.
seen = set()
rows = []
for name, code in table:
    if name in seen:
        continue
    seen.add(name)
    rows.append((name, code))
rows.sort()

body = []
for i in range(0, len(rows), 4):
    body.append('    ' + ' '.join('("%s",%#x),' % r for r in rows[i:i + 4]) + '\n')

header = '''//! ZapfDingbats glyph names.
//!
//! The Adobe Glyph List does not name the dingbats: they carry their own
//! list: every name in it is `a` followed by a number, from `a1` (a
//! scissors) to `a206`. A Type 1 Dingbats font names every glyph that way,
//! so without this table it scans as covering nothing but space, and no
//! symbol ever falls back to it.
//!
//! The `aNNN` shape means the list cannot collide with the Adobe Glyph List
//! proper, which is why FreeType can consult one combined table.
//!
//! Generated by `tools/gen_zapf.py` from Adobe's `zapfdingbats.txt`:
//! %d names.

/// Name to codepoint, sorted, so a lookup is a binary search.
#[rustfmt::skip]
static NAMES: [(&str, u32); %d] = [
''' % (len(rows), len(rows))

tail = '''];

/// The codepoint a ZapfDingbats glyph name stands for.
pub fn codepoint(name: &str) -> Option<u32> {
    NAMES.binary_search_by_key(&name, |(n, _)| n).ok().map(|index| NAMES[index].1)
}

#[cfg(test)]
mod tests {
    use super::{codepoint, NAMES};

    #[test]
    fn the_table_is_sorted_for_binary_search() {
        for pair in NAMES.windows(2) {
            assert!(pair[0].0 < pair[1].0, "{:?} then {:?}", pair[0], pair[1]);
        }
    }

    #[test]
    fn the_dingbats_are_named() {
        assert_eq!(codepoint("a1"), Some(0x2701)); // upper-blade scissors
        assert_eq!(codepoint("a120"), Some(0x2460)); // circled 1
        assert_eq!(codepoint("a206"), Some(0x2770)); // the last one
    }

    /// Nothing outside the `aNNN` shape is answered here: an ordinary name
    /// belongs to the Adobe Glyph List, and the two never overlap.
    #[test]
    fn other_names_are_not_answered() {
        assert_eq!(codepoint("A"), None);
        assert_eq!(codepoint("space"), None);
        assert_eq!(codepoint("a207"), None);
    }
}
'''

emit(OUT, header, body, tail)

print('generated %d dingbat names' % len(rows))
