"""Generate src/casefold.rs from the CaseFolding.txt fontconfig ships.

Run from the repo root:  python tools/gen_casefold.py
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from emit import emit  # noqa: E402

SRC = 'tools/data/fontconfig-2.17.0/fc-case/CaseFolding.txt'  # from the fontconfig checkout
OUT = 'src/casefold.rs'

single, multi, version = [], [], None
with io.open(SRC, encoding='utf-8') as f:
    for line in f:
        if version is None and 'CaseFolding-' in line:
            version = line.strip().lstrip('# ').strip()
        line = line.split('#')[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(';')]
        if len(parts) < 3:
            continue
        code, cls, mapping = parts[0], parts[1], parts[2]
        # fc-case.py keeps exactly the Common and Full classes.
        if cls not in ('C', 'F'):
            continue
        src_cp = int(code, 16)
        dst = [int(x, 16) for x in mapping.split()]
        (single if len(dst) == 1 else multi).append(
            (src_cp, dst[0] if len(dst) == 1 else dst))

single.sort()
multi.sort()
assert all(single[i][0] < single[i + 1][0] for i in range(len(single) - 1))
assert all(multi[i][0] < multi[i + 1][0] for i in range(len(multi) - 1))

BS = chr(92)  # backslash, kept out of the f-strings below


def ch(cp):
    return "'" + BS + "u{%04x}'" % cp


header = '''//! Unicode case folding, as fontconfig compares strings.
//!
//! Fontconfig folds with the Common and Full classes of `CaseFolding.txt` --
//! see `fc-case/fc-case.py`, which keeps exactly `C` and `F`. That is *case
//! folding*, not lowercasing, and the difference is load-bearing: the sharp s
//! folds to `ss`, the `fi` ligature folds to `fi`, and Greek final sigma folds
//! together with medial sigma. Rust's `str::to_lowercase` implements full
//! Unicode *lowercase* mapping, which leaves all three unchanged, so it cannot
//! stand in for this.
//!
//! Generated by `tools/gen_casefold.py` from the copy of
//! `%s` that fontconfig itself ships, so a fold here is
//! the fold fontconfig would have done for the same release.

/// Single-character folds, sorted by source codepoint.
#[rustfmt::skip]
static SINGLE: [(u32, u32); %d] = [
''' % (version, len(single))

body = []
for i in range(0, len(single), 4):
    row = ' '.join('(%#07x, %#07x),' % (a, b) for a, b in single[i:i + 4])
    body.append('    ' + row + '\n')

mid = '''];

/// Folds that expand to more than one character, sorted by source codepoint.
#[rustfmt::skip]
static MULTI: [(u32, &[char]); %d] = [
''' % len(multi)

mbody = []
for a, ds in multi:
    mbody.append('    (%#07x, &[%s]),\n' % (a, ', '.join(ch(d) for d in ds)))

tail = r'''];

/// The case-folded form of `c`, as one or more characters.
///
/// ASCII is answered without touching either table. That is not a
/// micro-optimisation: the tables are 104 and 1426 entries, so a character
/// that folds to itself was costing two binary searches -- about eighteen
/// branchy probes -- to work out what `c | 0x20` already knew. Font family
/// names are almost entirely ASCII, and folding them was over half the cost
/// of a match. The equivalence is checked exhaustively over all 128 of them
/// in the tests below.
pub fn fold(c: char) -> impl Iterator<Item = char> {
    let cp = c as u32;
    if c.is_ascii() {
        return Folded::One(Some(c.to_ascii_lowercase()));
    }
    let multi = MULTI.binary_search_by_key(&cp, |(from, _)| *from).ok();
    let mut expansion = multi.map(|i| MULTI[i].1.iter().copied());
    let mut plain = match multi {
        Some(_) => None,
        None => Some(
            SINGLE
                .binary_search_by_key(&cp, |(from, _)| *from)
                .ok()
                .and_then(|i| char::from_u32(SINGLE[i].1))
                .unwrap_or(c),
        ),
    };
    Folded::Table(std::iter::from_fn(move || {
        if let Some(chars) = &mut expansion {
            if let Some(c) = chars.next() {
                return Some(c);
            }
        }
        plain.take()
    }))
}

/// What [`fold`] yields: one character, or whatever the tables say.
///
/// An enum rather than a boxed iterator so the ASCII arm stays a move of one
/// `Option` and nothing is allocated.
enum Folded<I> {
    One(Option<char>),
    Table(I),
}

impl<I: Iterator<Item = char>> Iterator for Folded<I> {
    type Item = char;

    fn next(&mut self) -> Option<char> {
        match self {
            Self::One(c) => c.take(),
            Self::Table(iter) => iter.next(),
        }
    }
}

/// The case-folded characters of `s`.
pub fn fold_str(s: &str) -> impl Iterator<Item = char> + '_ {
    s.chars().flat_map(fold)
}

/// Whether two strings are equal after case folding.
pub fn eq(a: &str, b: &str) -> bool {
    fold_str(a).eq(fold_str(b))
}

/// Whether two strings are equal after case folding and dropping all blanks.
///
/// This is `FcStrCmpIgnoreBlanksAndCase`: fontconfig skips blanks *before*
/// folding, so a blank that a fold would introduce is not itself skipped.
pub fn eq_ignoring_blanks(a: &str, b: &str) -> bool {
    // Bytes, in one pass, for as long as both sides stay ASCII. Checking
    // that up front instead would walk both strings before comparing them,
    // and this is called once per font per property.
    //
    // The moment either side leaves ASCII the whole comparison restarts
    // through the tables. It has to be both sides and not either: a
    // character outside ASCII can still fold *into* it -- U+212A KELVIN SIGN
    // folds to `k` -- so byte comparison would miss a real match.
    let (x, y) = (a.as_bytes(), b.as_bytes());
    let (mut i, mut j) = (0usize, 0usize);
    loop {
        while x.get(i) == Some(&BLANK_BYTE) {
            i += 1;
        }
        while y.get(j) == Some(&BLANK_BYTE) {
            j += 1;
        }
        match (x.get(i), y.get(j)) {
            (None, None) => return true,
            (Some(l), Some(r)) if l.is_ascii() && r.is_ascii() => {
                if !l.eq_ignore_ascii_case(r) {
                    return false;
                }
                i += 1;
                j += 1;
            }
            // One of them is a continuation or a lead byte: start again the
            // long way, over characters rather than bytes.
            (Some(l), Some(r)) if !l.is_ascii() || !r.is_ascii() => {
                return nonblank(a).eq(nonblank(b));
            }
            // One side ended where the other did not.
            _ => return false,
        }
    }
}

/// [`BLANK`] as the byte it is, since the fast path works in bytes.
const BLANK_BYTE: u8 = BLANK as u8;

/// A hash of `s` in the same terms [`eq_ignoring_blanks`] compares it.
///
/// Two strings that compare equal hash equal, which is all a lookup table
/// needs; the reverse is not promised, so a table keyed by this has to
/// confirm a hit with [`eq_ignoring_blanks`]. Fontconfig keys its family
/// table the same way, with `FcStrHashIgnoreBlanksAndCase`.
///
/// Nothing is allocated: the folded characters are consumed as they come.
pub fn hash_ignoring_blanks(s: &str) -> u64 {
    // FNV-1a. The table is a few hundred entries at most and the keys are
    // short, so what matters is that this does not allocate.
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut eat = |byte: u8| {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    };
    // An ASCII string folds byte for byte, so it can be hashed without
    // decoding characters or consulting a table. The two paths have to agree
    // exactly, since a name reached by one is looked up by the other.
    if s.is_ascii() {
        for byte in s.as_bytes().iter().filter(|c| **c != BLANK as u8) {
            eat(byte.to_ascii_lowercase());
        }
        return hash;
    }
    for c in nonblank(s) {
        let mut buffer = [0u8; 4];
        for byte in c.encode_utf8(&mut buffer).as_bytes() {
            eat(*byte);
        }
    }
    hash
}

/// The folded characters of `s`, with blanks dropped first.
fn nonblank(s: &str) -> impl Iterator<Item = char> + '_ {
    s.chars().filter(|c| *c != BLANK).flat_map(fold)
}

/// The only character fontconfig skips when ignoring blanks.
///
/// `FcStrCaseWalkerNextNonBlank` skips exactly `' '` -- not tab, and not the
/// wider set `char::is_whitespace` covers. It skips on the source text, before
/// folding, so a fold that produced a space would not itself be skipped.
const BLANK: char = ' ';
/// The ASCII fast paths, which are only sound if they answer exactly what
/// the tables would have.
'''

TESTS = r'''#[cfg(test)]
mod ascii_tests {
    use super::{eq_ignoring_blanks, fold, hash_ignoring_blanks, nonblank, BLANK};

    /// Every ASCII character, against the tables it now skips.
    ///
    /// This is the whole argument for the fast path: not that ASCII folding
    /// is obviously lowercasing, but that these tables say so for all 128.
    #[test]
    fn ascii_folds_the_way_the_tables_would() {
        for cp in 0u32..128 {
            let c = char::from_u32(cp).expect("ascii");
            let got: Vec<char> = fold(c).collect();
            assert_eq!(got, vec![c.to_ascii_lowercase()], "{cp:#04x}");
        }
    }

    /// A blank is skipped before folding, so it must not survive either path.
    #[test]
    fn a_blank_is_skipped_on_both_paths() {
        assert!(eq_ignoring_blanks("a b", "ab"));
        assert_eq!(hash_ignoring_blanks("a b"), hash_ignoring_blanks("ab"));
        assert_eq!(BLANK, ' ');
    }

    /// A character outside ASCII can fold into it, which is why the fast
    /// path needs *both* sides to be ASCII rather than either.
    #[test]
    fn a_non_ascii_character_can_fold_into_ascii() {
        // U+212A KELVIN SIGN folds to `k`.
        assert!(eq_ignoring_blanks("K", "\u{212a}"));
        assert!(eq_ignoring_blanks("\u{212a}", "k"));
        assert_eq!(hash_ignoring_blanks("k"), hash_ignoring_blanks("\u{212a}"));
    }

    /// The two hash paths have to agree, or a name inserted by one would be
    /// looked up in the wrong bucket by the other.
    #[test]
    fn both_hash_paths_agree() {
        for name in [
            "DejaVu Sans",
            "dejavusans",
            "DEJAVU  SANS",
            "Noto Sans CJK JP",
            "\u{212a}elvin",
            "Kelvin",
            "\u{fb00}",
            "ff",
        ] {
            // Recompute the general way, whatever the input.
            let mut expected: u64 = 0xcbf2_9ce4_8422_2325;
            for c in nonblank(name) {
                let mut buffer = [0u8; 4];
                for byte in c.encode_utf8(&mut buffer).as_bytes() {
                    expected ^= u64::from(*byte);
                    expected = expected.wrapping_mul(0x100_0000_01b3);
                }
            }
            assert_eq!(hash_ignoring_blanks(name), expected, "{name}");
        }
    }

    /// Equal strings hash equal, which is the only promise the table needs.
    #[test]
    fn equal_names_hash_equal() {
        let pairs = [
            ("DejaVu Sans", "dejavusans"),
            ("Noto Sans", "NOTO SANS"),
            ("\u{fb00}", "ff"),
            ("K", "\u{212a}"),
        ];
        for (a, b) in pairs {
            assert!(eq_ignoring_blanks(a, b), "{a} vs {b}");
            assert_eq!(hash_ignoring_blanks(a), hash_ignoring_blanks(b), "{a} vs {b}");
        }
    }

    #[test]
    fn different_names_still_differ() {
        assert!(!eq_ignoring_blanks("DejaVu Sans", "DejaVu Serif"));
        assert!(!eq_ignoring_blanks("a", "ab"));
        assert!(!eq_ignoring_blanks("ab", "a"));
        assert!(!eq_ignoring_blanks("", "a"));
        assert!(eq_ignoring_blanks("", ""));
        assert!(eq_ignoring_blanks("   ", ""));
    }
}

#[cfg(test)]
mod tests {
    use super::{eq, eq_ignoring_blanks, fold_str};

    fn folded(s: &str) -> String {
        fold_str(s).collect()
    }

    #[test]
    fn ascii_folds_to_lowercase() {
        assert_eq!(folded("DejaVu Sans"), "dejavu sans");
        assert!(eq("DEJAVU SANS", "dejavu sans"));
        assert!(!eq("DejaVu", "DejaVv"));
    }

    /// The three cases that separate folding from lowercasing. Rust's
    /// `to_lowercase` leaves every one of them unchanged.
    #[test]
    fn folding_is_not_lowercasing() {
        for (input, folds_to) in [
            ("stra\u{00df}e", "strasse"), // U+00DF LATIN SMALL LETTER SHARP S
            ("STRA\u{1e9e}E", "strasse"), // U+1E9E LATIN CAPITAL LETTER SHARP S
            ("\u{fb01}n", "fin"),         // U+FB01 LATIN SMALL LIGATURE FI
            ("\u{03c2}", "\u{03c3}"),     // final sigma folds with medial sigma
        ] {
            assert_eq!(folded(input), folds_to, "folding {input:?}");
            assert_ne!(
                input.to_lowercase(),
                folds_to,
                "if to_lowercase handled {input:?}, this table would be unnecessary"
            );
        }
        assert!(eq("Stra\u{00df}e", "STRASSE"));
        assert!(eq("\u{fb01}", "fi"));
    }

    #[test]
    fn non_ascii_single_folds() {
        assert!(eq("\u{0410}\u{0411}", "\u{0430}\u{0431}")); // Cyrillic А Б / а б
        assert!(eq("\u{0391}\u{0392}", "\u{03b1}\u{03b2}")); // Greek Α Β / α β
        assert!(eq("\u{00c9}", "\u{00e9}")); // É / é
    }

    /// Only the space character is a blank, and it is skipped before folding.
    #[test]
    fn blanks_are_only_spaces() {
        assert!(eq_ignoring_blanks("  dejavu sans  ", "DejaVuSans"));
        assert!(eq_ignoring_blanks("DejaVu Sans", "dejavusans"));
        // A tab is not a blank, so these differ.
        assert!(!eq_ignoring_blanks("DejaVu\tSans", "DejaVuSans"));
        // Ignoring blanks still folds.
        assert!(eq_ignoring_blanks("STRA \u{00df} E", "strasse"));
    }

    #[test]
    fn characters_that_fold_to_themselves_pass_through() {
        assert_eq!(folded("abc123-_"), "abc123-_");
        assert_eq!(folded("\u{4e00}\u{4e8c}"), "\u{4e00}\u{4e8c}");
        assert_eq!(folded(""), "");
    }
}
'''

emit(OUT, header, body, mid, mbody, tail, TESTS)

print('generated %d single + %d multi folds from %s' % (len(single), len(multi), version))
