"""Generate src/langs.rs from fontconfig's fc-lang orthography list.

Two orders are in play, and conflating them decodes every langset wrongly.

`fcLangCharSets[]` is sorted by language name, and `FcLangSetIndex` binary
searches it. But `FcLangSetBitGet` does not index the bitmap with that
position: it maps through `fcLangCharSetIndices[]` first, which fc-lang.py
fills with `orth_entries[fn]` -- the index of the orth file in the *unsorted*
declaration list in meson.build. So the bit position is declaration order.
`FcNameUnparseLangSet` confirms it from the other side: it walks bit
positions in order and maps each back through `fcLangCharSetIndicesInv[]` to
get a name, which is why `fc-list` prints `ba|bm|be|bg`.

So LANGS is in bit (declaration) order, and SORTED ranks those bit indices
by name for lookup.

Run from the repo root:  python tools/gen_langs.py
"""
import io
import re

SRC = 'reference/fc-2.17.0/fc-lang/meson.build'
OUT = 'src/langs.rs'
RELEASE = '2.17.0'

with io.open(SRC, encoding='utf-8') as f:
    text = f.read()

# The list is `orth_files = [ 'aa.orth', ... ]`; take only that array.
start = text.index('orth_files')
end = text.index(']', start)
files = re.findall(r"'([^']+\.orth)'", text[start:end])
assert files, 'no orth files found'

# Declaration order is bit order. get_lang(get_name(fn)) is the stem with
# '_' turned into '-', lowercased.
langs = [fn.split('.')[0].replace('_', '-').replace(' ', '').lower() for fn in files]
assert len(langs) == len(set(langs)), 'duplicate language names'
assert langs != sorted(langs), 'declaration order is unexpectedly sorted'

# Rank the bit indices by name, for the binary search fontconfig does over
# its sorted table.
sorted_bits = sorted(range(len(langs)), key=lambda i: langs[i])

words = (len(langs) + 31) // 32

body = []
for i in range(0, len(langs), 6):
    body.append('    ' + ' '.join('"%s",' % l for l in langs[i:i + 6]) + '\n')

sorted_body = []
for i in range(0, len(sorted_bits), 12):
    sorted_body.append('    ' + ' '.join('%d,' % b for b in sorted_bits[i:i + 12]) + '\n')

header = '''//! Fontconfig's language list, in the order a serialized langset indexes it.
//!
//! A `FcLangSet` in a cache is a bare bitmap -- fontconfig does not serialize
//! the `extra` string set alongside it -- so bit `i` means "this font covers
//! [`LANGS`]`[i]`", and nothing in the file says which list was meant.
//!
//! # Two orders
//!
//! [`LANGS`] is in *bit* order, which is the order the orthography files are
//! declared in fontconfig's `fc-lang/meson.build`, and that list is not
//! sorted. Fontconfig keeps its own `fcLangCharSets` sorted by name and maps
//! a position in it through `fcLangCharSetIndices` to reach the bit, which
//! this module mirrors. Using the sorted order as the bit order decodes every
//! langset wrongly, and plausibly enough to look right.
//!
//! # This table is an assumption about the writer
//!
//! Reordering or removing a language shifts every bit after it, and the cache
//! format version does not change when the list changes: version 9 was
//! written by 2.15.0 with 279 languages, and by 2.16.0 and 2.17.0 with %d.
//!
//! This table is %s's. Reading a cache written by a different release can
//! silently mislabel languages, and a version 9 cache cannot be asked which
//! release wrote it -- fontconfig only began recording that in the header
//! after 2.17. The one detectable case is a bit set past the end of this
//! table, which can only mean the writer knew more languages than we do;
//! [`LangSet::is_consistent`](crate::LangSet::is_consistent) reports it.
//!
//! Generated by `tools/gen_langs.py`.

/// The fontconfig release this table was taken from.
pub const RELEASE: &str = "%s";

/// How many 32-bit words a serialized langset bitmap occupies.
///
/// `NUM_LANG_SET_MAP` in the generated `fclang.h`, which is
/// `(languages + 31) / 32`.
pub const MAP_WORDS: usize = %d;

/// Every language fontconfig knows an orthography for, indexed by bit.
#[rustfmt::skip]
pub static LANGS: [&str; %d] = [
''' % (len(langs), RELEASE, RELEASE, words, len(langs))

mid = '''];

/// Bit indices ordered by language name, for lookup.
///
/// `LANGS[SORTED[k]]` is the k-th language alphabetically.
#[rustfmt::skip]
pub(crate) static SORTED: [u16; %d] = [
''' % len(langs)

tail = '''];

/// The name of the `rank`-th language alphabetically.
pub fn nth_sorted(rank: usize) -> Option<&'static str> {
    LANGS.get(*SORTED.get(rank)? as usize).copied()
}

/// The bit index of the `rank`-th language alphabetically.
pub fn bit_of_rank(rank: usize) -> Option<usize> {
    SORTED.get(rank).map(|bit| *bit as usize)
}

/// Where `lang` sits alphabetically: its rank if known, else where it would go.
pub fn rank_of(lang: &str) -> std::result::Result<usize, usize> {
    // Folded as it is compared, rather than by lowercasing a copy first.
    // Scoring asks this once per font per language, so the copy was an
    // allocation on the hottest path there is.
    SORTED.binary_search_by(|bit| cmp_ignoring_ascii_case(LANGS[*bit as usize], lang))
}

/// Order two language tags without regard to case, and without allocating.
///
/// The table is lowercase already -- there is a test -- so this only has to
/// fold the side that came from a caller. Folding both costs nothing and
/// means the ordering does not depend on that fact staying true.
fn cmp_ignoring_ascii_case(a: &str, b: &str) -> std::cmp::Ordering {
    let mut a = a.bytes().map(|c| c.to_ascii_lowercase());
    let mut b = b.bytes().map(|c| c.to_ascii_lowercase());
    loop {
        match (a.next(), b.next()) {
            (None, None) => return std::cmp::Ordering::Equal,
            (None, Some(_)) => return std::cmp::Ordering::Less,
            (Some(_), None) => return std::cmp::Ordering::Greater,
            (Some(x), Some(y)) if x == y => {}
            (Some(x), Some(y)) => return x.cmp(&y),
        }
    }
}

/// The bit index of `lang`, matched case-insensitively.
pub fn index_of(lang: &str) -> Option<usize> {
    rank_of(lang).ok().and_then(bit_of_rank)
}

#[cfg(test)]
mod tests {
    use super::{index_of, nth_sorted, rank_of, LANGS, MAP_WORDS, SORTED};

    /// The table is lowercase, which is what lets a lookup fold only the
    /// caller's side and still order the same way.
    #[test]
    fn every_language_name_is_lowercase() {
        for lang in LANGS {
            assert_eq!(*lang, lang.to_ascii_lowercase(), "{lang}");
        }
    }

    /// A lookup ignores case, and does so without a copy.
    #[test]
    fn a_lookup_ignores_case() {
        for spelling in ["zh-tw", "ZH-TW", "Zh-Tw"] {
            assert_eq!(rank_of(spelling), rank_of("zh-tw"), "{spelling}");
            assert_eq!(index_of(spelling), index_of("zh-tw"), "{spelling}");
        }
    }

    /// A tag that is not there lands where it would be inserted, which is
    /// what the outward walk in `has_lang` starts from.
    #[test]
    fn a_missing_tag_reports_its_insertion_point() {
        let at = rank_of("en-gb").expect_err("not in the table");
        let before = nth_sorted(at.saturating_sub(1)).expect("a neighbour");
        assert!(before <= "en-gb", "{before} should sort before en-gb");
        if let Some(after) = nth_sorted(at) {
            assert!(after >= "en-gb", "{after} should sort after en-gb");
        }
    }

    /// Bit order is fontconfig's declaration order, and it is not sorted.
    /// `bm` really does come before `be`, which is the cheapest way to tell
    /// the two orders apart -- and the thing `fc-list` output shows directly.
    #[test]
    fn bit_order_is_declaration_order_not_alphabetical() {
        let bm = index_of("bm").expect("bm");
        let be = index_of("be").expect("be");
        assert!(bm < be, "bm at {bm}, be at {be}");
        assert!(LANGS.windows(2).any(|w| w[0] > w[1]), "LANGS must not be sorted");
    }

    #[test]
    fn the_sorted_view_is_sorted_and_is_a_permutation() {
        assert_eq!(SORTED.len(), LANGS.len());
        let names: Vec<&str> = SORTED.iter().map(|b| LANGS[*b as usize]).collect();
        assert!(names.windows(2).all(|w| w[0] < w[1]), "SORTED is not sorted");
        let mut bits: Vec<u16> = SORTED.to_vec();
        bits.sort_unstable();
        bits.dedup();
        assert_eq!(bits.len(), LANGS.len(), "SORTED must cover every bit once");
    }

    #[test]
    fn lookup_round_trips_through_both_orders() {
        for (bit, lang) in LANGS.iter().enumerate() {
            assert_eq!(index_of(lang), Some(bit), "{lang}");
        }
        for rank in 0..SORTED.len() {
            let name = nth_sorted(rank).expect("in range");
            assert_eq!(rank_of(name), Ok(rank), "{name}");
        }
    }

    #[test]
    fn well_known_languages_are_present() {
        for lang in ["en", "de", "fr", "ru", "ja", "ko", "ar", "fa", "hi", "th"] {
            assert!(index_of(lang).is_some(), "{lang} missing");
        }
        assert_eq!(index_of("EN"), index_of("en"));
        assert_eq!(index_of("not-a-language"), None);
    }

    #[test]
    fn the_bitmap_is_wide_enough_for_every_language() {
        assert_eq!(MAP_WORDS, LANGS.len().div_ceil(32));
        assert!(LANGS.len() <= MAP_WORDS * 32);
    }

    #[test]
    fn names_are_lowercase_and_use_hyphens() {
        for lang in LANGS {
            assert_eq!(lang, lang.to_lowercase(), "{lang}");
            assert!(!lang.contains('_'), "{lang}");
        }
    }
}
'''

with io.open(OUT, 'w', encoding='utf-8', newline='\n') as out:
    out.write(header)
    out.writelines(body)
    out.write(mid)
    out.writelines(sorted_body)
    out.write(tail)

print('generated %d languages, %d map words, from %s' % (len(langs), words, RELEASE))
