"""Generate src/orth.rs from fontconfig's fc-lang orthography files.

Each `.orth` file lists the codepoints a language needs, as single values or
ranges, and may `include` another file. A font supports a language when it
covers every one of them -- that is the whole of `FcLangSetFromCharSet`.

The tables are emitted in *bit* order, matching src/langs.rs, so entry `i`
here is the orthography for `LANGS[i]`.

Run from the repo root:  python tools/gen_orth.py
"""
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from emit import emit  # noqa: E402
import os
import re

SRC_DIR = 'tools/data/fontconfig-2.17.0/fc-lang'
MESON = os.path.join(SRC_DIR, 'meson.build')
OUT = 'src/orth.rs'
RELEASE = '2.17.0'

with io.open(MESON, encoding='utf-8') as f:
    text = f.read()
start = text.index('orth_files')
end = text.index(']', start)
files = re.findall(r"'([^']+\.orth)'", text[start:end])
assert files, 'no orth files found'

# Two notations are in use: bare hex like `0041-005a` in most files, and
# `0x3000` in the CJK ones. Reading only the first silently produced empty
# orthographies for Japanese, Korean and Chinese -- which would have made
# every font claim to support them.
LINE = re.compile(
    r'^(?:0[xX])?([0-9a-fA-F]{2,6})'
    r'(?:\s*-\s*(?:0[xX])?([0-9a-fA-F]{2,6}))?')


def parse(name, seen=None):
    """Codepoint ranges for one orth file, following `include` lines."""
    seen = set() if seen is None else seen
    if name in seen:
        return []
    seen.add(name)
    path = os.path.join(SRC_DIR, name)
    ranges = []
    with io.open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.split('#')[0].strip()
            if not line:
                continue
            if line.startswith('include '):
                ranges += parse(line[8:].strip(), seen)
                continue
            m = LINE.match(line)
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            ranges.append((lo, hi))
    return ranges


def normalize(ranges):
    """Sort and merge overlapping or adjacent ranges."""
    if not ranges:
        return []
    ranges = sorted(ranges)
    out = [list(ranges[0])]
    for lo, hi in ranges[1:]:
        if lo <= out[-1][1] + 1:
            out[-1][1] = max(out[-1][1], hi)
        else:
            out.append([lo, hi])
    return [tuple(r) for r in out]


tables = [(fn, normalize(parse(fn))) for fn in files]
total = sum(len(r) for _, r in tables)

# One flat range array, with each language a slice of it. A per-language
# `&[(u32, u32)]` would cost a fat pointer each and scatter the data.
flat = []
spans = []
for _, ranges in tables:
    spans.append((len(flat), len(ranges)))
    flat += ranges

header = '''//! Which codepoints each language needs, from fontconfig's `fc-lang` data.
//!
//! A font supports a language when it covers every codepoint in that
//! language's orthography, and nothing less: that single rule is all of
//! `FcLangSetFromCharSet`. The orthographies are deliberately small -- English
//! is the letters, the accented forms it borrows, and its punctuation -- so
//! this is a question about coverage, not about how many characters a font has.
//!
//! Entry `i` is the orthography for [`LANGS`](crate::langs::LANGS)`[i]`, so the
//! two tables share fontconfig's declaration order and are generated from the
//! same list.
//!
//! Generated by `tools/gen_orth.py` from fontconfig %s: %d ranges across
//! %d languages.

/// Where each language's ranges sit in [`RANGES`]: offset and count.
#[rustfmt::skip]
static SPANS: [(u32, u32); %d] = [
''' % (RELEASE, total, len(tables), len(spans))

body = []
for i in range(0, len(spans), 8):
    body.append('    ' + ' '.join('(%d,%d),' % s for s in spans[i:i + 8]) + '\n')

mid = '''];

/// Every orthography's ranges, inclusive, concatenated.
#[rustfmt::skip]
static RANGES: [(u32, u32); %d] = [
''' % len(flat)

rbody = []
for i in range(0, len(flat), 6):
    rbody.append('    ' + ' '.join('(%#x,%#x),' % r for r in flat[i:i + 6]) + '\n')

tail = '''];

/// The codepoint ranges language `index` needs, inclusive.
pub fn orthography(index: usize) -> &'static [(u32, u32)] {
    match SPANS.get(index) {
        Some((offset, count)) => &RANGES[*offset as usize..*offset as usize + *count as usize],
        None => &[],
    }
}

/// How many languages have an orthography here.
pub fn len() -> usize {
    SPANS.len()
}

#[cfg(test)]
mod tests {
    use super::{len, orthography, RANGES};

    #[test]
    fn every_language_has_an_orthography() {
        assert_eq!(len(), crate::langs::LANGS.len());
        for index in 0..len() {
            assert!(!orthography(index).is_empty(), "{index} is empty");
        }
    }

    #[test]
    fn ranges_are_sorted_and_disjoint() {
        for index in 0..len() {
            let ranges = orthography(index);
            for range in ranges {
                assert!(range.0 <= range.1, "{range:?} is inverted");
            }
            for pair in ranges.windows(2) {
                assert!(
                    pair[0].1 + 1 < pair[1].0,
                    "{:?} and {:?} should have been merged",
                    pair[0],
                    pair[1]
                );
            }
        }
    }

    /// English needs the basic Latin letters and little else -- an
    /// orthography is what a language *requires*, not everything it can use.
    #[test]
    fn english_is_small_and_covers_the_alphabet() {
        let index = crate::langs::index_of("en").expect("en");
        let ranges = orthography(index);
        let covers = |c: char| ranges.iter().any(|(lo, hi)| (*lo..=*hi).contains(&(c as u32)));
        for c in ['A', 'Z', 'a', 'z'] {
            assert!(covers(c), "{c} missing from the English orthography");
        }
        assert!(!covers('\\u{4e00}'), "English should not need Han");
    }

    #[test]
    fn every_codepoint_is_in_range() {
        for (_lo, hi) in RANGES {
            assert!(hi <= 0x10ffff, "{hi:#x} is past the last codepoint");
        }
    }
}
'''

emit(OUT, header, body, mid, rbody, tail)

print('generated %d ranges across %d languages' % (total, len(tables)))
