"""Generate src/casefold.rs from the CaseFolding.txt fontconfig ships.

Run from the repo root:  python tools/gen_casefold.py
"""
import io

SRC = 'reference/fc-2.17.0/fc-case/CaseFolding.txt'  # from the fontconfig checkout
OUT = 'src/casefold.rs'

single, multi, version = [], [], None
with io.open(SRC, encoding='utf-8') as f:
    for line in f:
        if version is None and 'CaseFolding-' in line:
            version = line.strip().lstrip('# ').strip()
        line = line.split('#')[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(';')]
        if len(parts) < 3:
            continue
        code, cls, mapping = parts[0], parts[1], parts[2]
        # fc-case.py keeps exactly the Common and Full classes.
        if cls not in ('C', 'F'):
            continue
        src_cp = int(code, 16)
        dst = [int(x, 16) for x in mapping.split()]
        (single if len(dst) == 1 else multi).append(
            (src_cp, dst[0] if len(dst) == 1 else dst))

single.sort()
multi.sort()
assert all(single[i][0] < single[i + 1][0] for i in range(len(single) - 1))
assert all(multi[i][0] < multi[i + 1][0] for i in range(len(multi) - 1))

BS = chr(92)  # backslash, kept out of the f-strings below


def ch(cp):
    return "'" + BS + "u{%04x}'" % cp


header = '''//! Unicode case folding, as fontconfig compares strings.
//!
//! Fontconfig folds with the Common and Full classes of `CaseFolding.txt` --
//! see `fc-case/fc-case.py`, which keeps exactly `C` and `F`. That is *case
//! folding*, not lowercasing, and the difference is load-bearing: the sharp s
//! folds to `ss`, the `fi` ligature folds to `fi`, and Greek final sigma folds
//! together with medial sigma. Rust's `str::to_lowercase` implements full
//! Unicode *lowercase* mapping, which leaves all three unchanged, so it cannot
//! stand in for this.
//!
//! Generated by `tools/gen_casefold.py` from the copy of
//! `%s` that fontconfig itself ships, so a fold here is
//! the fold fontconfig would have done for the same release.

/// Single-character folds, sorted by source codepoint.
static SINGLE: [(u32, u32); %d] = [
''' % (version, len(single))

body = []
for i in range(0, len(single), 4):
    row = ' '.join('(%#07x, %#07x),' % (a, b) for a, b in single[i:i + 4])
    body.append('    ' + row + '\n')

mid = '''];

/// Folds that expand to more than one character, sorted by source codepoint.
static MULTI: [(u32, &[char]); %d] = [
''' % len(multi)

mbody = []
for a, ds in multi:
    mbody.append('    (%#07x, &[%s]),\n' % (a, ', '.join(ch(d) for d in ds)))

tail = '''];

/// The case-folded form of `c`, as one or more characters.
///
/// A character that folds to itself -- the common case -- costs one binary
/// search and yields itself unchanged.
pub fn fold(c: char) -> impl Iterator<Item = char> {
    let cp = c as u32;
    let multi = MULTI.binary_search_by_key(&cp, |(from, _)| *from).ok();
    let mut expansion = multi.map(|i| MULTI[i].1.iter().copied());
    let mut plain = match multi {
        Some(_) => None,
        None => Some(
            SINGLE
                .binary_search_by_key(&cp, |(from, _)| *from)
                .ok()
                .and_then(|i| char::from_u32(SINGLE[i].1))
                .unwrap_or(c),
        ),
    };
    std::iter::from_fn(move || {
        if let Some(chars) = &mut expansion {
            if let Some(c) = chars.next() {
                return Some(c);
            }
        }
        plain.take()
    })
}

/// The case-folded characters of `s`.
pub fn fold_str(s: &str) -> impl Iterator<Item = char> + '_ {
    s.chars().flat_map(fold)
}

/// Whether two strings are equal after case folding.
pub fn eq(a: &str, b: &str) -> bool {
    fold_str(a).eq(fold_str(b))
}

/// Whether two strings are equal after case folding and dropping all blanks.
///
/// This is `FcStrCmpIgnoreBlanksAndCase`: fontconfig skips blanks *before*
/// folding, so a blank that a fold would introduce is not itself skipped.
pub fn eq_ignoring_blanks(a: &str, b: &str) -> bool {
    nonblank(a).eq(nonblank(b))
}

/// The folded characters of `s`, with blanks dropped first.
fn nonblank(s: &str) -> impl Iterator<Item = char> + '_ {
    s.chars().filter(|c| *c != BLANK).flat_map(fold)
}

/// The only character fontconfig skips when ignoring blanks.
///
/// `FcStrCaseWalkerNextNonBlank` skips exactly `' '` -- not tab, and not the
/// wider set `char::is_whitespace` covers. It skips on the source text, before
/// folding, so a fold that produced a space would not itself be skipped.
const BLANK: char = ' ';
'''

with io.open(OUT, 'w', encoding='utf-8', newline='\n') as out:
    out.write(header)
    out.writelines(body)
    out.write(mid)
    out.writelines(mbody)
    out.write(tail)

print('generated %d single + %d multi folds from %s' % (len(single), len(multi), version))
