//! Fontconfig's language list, in the order a serialized langset indexes it.
//!
//! A `FcLangSet` in a cache is a bare bitmap -- fontconfig does not serialize
//! the `extra` string set alongside it -- so bit `i` means "this font covers
//! [`LANGS`]`[i]`", and nothing in the file says which list was meant.
//!
//! # Two orders
//!
//! [`LANGS`] is in *bit* order, which is the order the orthography files are
//! declared in fontconfig's `fc-lang/meson.build`, and that list is not
//! sorted. Fontconfig keeps its own `fcLangCharSets` sorted by name and maps
//! a position in it through `fcLangCharSetIndices` to reach the bit;
//! [`SORTED`] is that mapping. Using the sorted order as the bit order
//! decodes every langset wrongly, and plausibly enough to look right.
//!
//! # This table is an assumption about the writer
//!
//! Reordering or removing a language shifts every bit after it, and the cache
//! format version does not change when the list changes: version 9 was
//! written by 2.15.0 with 279 languages, and by 2.16.0 and 2.17.0 with 281.
//!
//! This table is 2.17.0's. Reading a cache written by a different release can
//! silently mislabel languages, and a version 9 cache cannot be asked which
//! release wrote it -- fontconfig only began recording that in the header
//! after 2.17. The one detectable case is a bit set past the end of this
//! table, which can only mean the writer knew more languages than we do;
//! [`LangSet::is_consistent`](crate::LangSet::is_consistent) reports it.
//!
//! Generated by `tools/gen_langs.py`.

/// The fontconfig release this table was taken from.
pub const RELEASE: &str = "2.17.0";

/// How many 32-bit words a serialized langset bitmap occupies.
///
/// `NUM_LANG_SET_MAP` in the generated `fclang.h`, which is
/// `(languages + 31) / 32`.
pub const MAP_WORDS: usize = 9;

/// Every language fontconfig knows an orthography for, indexed by bit.
pub static LANGS: [&str; 281] = [
    "aa", "ab", "af", "am", "ar", "as",
    "ast", "av", "ay", "az-az", "az-ir", "ba",
    "bm", "be", "bg", "bh", "bho", "bi",
    "bin", "bn", "bo", "br", "bs", "bua",
    "ca", "ce", "ch", "chm", "chr", "co",
    "cs", "cu", "cv", "cy", "da", "de",
    "dz", "el", "en", "eo", "es", "et",
    "eu", "fa", "fi", "fj", "fo", "fr",
    "ff", "fur", "fy", "ga", "gd", "gez",
    "gl", "gn", "gu", "gv", "ha", "haw",
    "he", "hi", "ho", "hr", "hu", "hy",
    "ia", "ig", "id", "ie", "ik", "io",
    "is", "it", "iu", "ja", "ka", "kaa",
    "ki", "kk", "kl", "km", "kn", "ko",
    "kok", "ks", "ku-am", "ku-ir", "kum", "kv",
    "kw", "ky", "la", "lb", "lez", "ln",
    "lo", "lt", "lv", "mg", "mh", "mi",
    "mk", "ml", "mn-cn", "mo", "mr", "mt",
    "my", "nb", "nds", "ne", "nl", "nn",
    "no", "nr", "nso", "ny", "oc", "om",
    "or", "os", "pa", "pl", "ps-af", "ps-pk",
    "pt", "rm", "ro", "ru", "sa", "sah",
    "sco", "se", "sel", "sh", "shs", "si",
    "sk", "sl", "sm", "sma", "smj", "smn",
    "sms", "so", "sq", "sr", "ss", "st",
    "sv", "sw", "syr", "ta", "te", "tg",
    "th", "ti-er", "ti-et", "tig", "tk", "tl",
    "tn", "to", "tr", "ts", "tt", "tw",
    "tyv", "ug", "uk", "ur", "uz", "ve",
    "vi", "vo", "vot", "wa", "wen", "wo",
    "xh", "yap", "yi", "yo", "zh-cn", "zh-hk",
    "zh-mo", "zh-sg", "zh-tw", "zu", "ak", "an",
    "ber-dz", "ber-ma", "byn", "crh", "csb", "dv",
    "ee", "fat", "fil", "hne", "hsb", "ht",
    "hz", "ii", "jv", "kab", "kj", "kr",
    "ku-iq", "ku-tr", "kwm", "lg", "li", "mai",
    "mn-mn", "ms", "na", "ng", "nv", "ota",
    "pa-pk", "pap-an", "pap-aw", "qu", "quz", "rn",
    "rw", "sc", "sd", "sg", "sid", "sn",
    "su", "ty", "wal", "za", "lah", "nqo",
    "brx", "sat", "doi", "mni", "und-zsye", "und-zmth",
    "anp", "bhb", "hif", "mag", "raj", "the",
    "agr", "ayc", "bem", "ckb", "cmn", "dsb",
    "hak", "lij", "lzh", "mfe", "mhr", "miq",
    "mjw", "mnw", "nan", "nhn", "niu", "rif",
    "sgs", "shn", "szl", "tcy", "tpi", "unm",
    "wae", "yue", "yuw", "got", "cop",
];

/// Bit indices ordered by language name, for lookup.
///
/// `LANGS[SORTED[k]]` is the k-th language alphabetically.
pub static SORTED: [u16; 281] = [
    0, 1, 2, 252, 190, 3, 191, 246, 4, 5, 6, 7,
    8, 253, 9, 10, 11, 13, 254, 192, 193, 14, 15, 247,
    16, 17, 18, 12, 19, 20, 21, 240, 22, 23, 194, 24,
    25, 26, 27, 28, 255, 256, 29, 280, 195, 30, 196, 31,
    32, 33, 34, 35, 242, 257, 197, 36, 198, 37, 38, 39,
    40, 41, 42, 43, 199, 48, 44, 200, 45, 46, 47, 49,
    50, 51, 52, 53, 54, 55, 279, 56, 57, 58, 258, 59,
    60, 61, 248, 201, 62, 63, 202, 203, 64, 65, 204, 66,
    68, 69, 67, 205, 70, 71, 72, 73, 74, 75, 206, 76,
    77, 207, 78, 208, 79, 80, 81, 82, 83, 84, 209, 85,
    86, 210, 87, 211, 88, 89, 90, 212, 91, 92, 238, 93,
    94, 213, 214, 259, 95, 96, 97, 98, 260, 249, 215, 261,
    99, 100, 262, 101, 263, 264, 102, 103, 104, 216, 243, 265,
    105, 106, 217, 107, 108, 218, 266, 109, 110, 111, 219, 267,
    268, 112, 113, 114, 239, 115, 116, 220, 117, 118, 119, 120,
    121, 221, 122, 222, 223, 224, 123, 124, 125, 126, 225, 226,
    250, 269, 127, 227, 128, 129, 228, 130, 131, 241, 229, 132,
    230, 133, 134, 231, 270, 135, 271, 136, 137, 232, 138, 139,
    140, 141, 142, 143, 144, 233, 145, 146, 147, 148, 149, 234,
    150, 151, 152, 272, 153, 273, 154, 155, 156, 251, 157, 158,
    159, 160, 161, 162, 163, 274, 164, 165, 166, 167, 235, 168,
    169, 170, 245, 244, 275, 171, 172, 173, 174, 175, 176, 177,
    276, 236, 178, 179, 180, 181, 182, 183, 277, 278, 237, 184,
    185, 186, 187, 188, 189,
];

/// The name of the `rank`-th language alphabetically.
pub fn nth_sorted(rank: usize) -> Option<&'static str> {
    LANGS.get(*SORTED.get(rank)? as usize).copied()
}

/// The bit index of the `rank`-th language alphabetically.
pub fn bit_of_rank(rank: usize) -> Option<usize> {
    SORTED.get(rank).map(|bit| *bit as usize)
}

/// Where `lang` sits alphabetically: its rank if known, else where it would go.
pub fn rank_of(lang: &str) -> std::result::Result<usize, usize> {
    // Folded as it is compared, rather than by lowercasing a copy first.
    // Scoring asks this once per font per language, so the copy was an
    // allocation on the hottest path there is.
    SORTED.binary_search_by(|bit| cmp_ignoring_ascii_case(LANGS[*bit as usize], lang))
}

/// Order two language tags without regard to case, and without allocating.
///
/// The table is lowercase already -- there is a test -- so this only has to
/// fold the side that came from a caller. Folding both costs nothing and
/// means the ordering does not depend on that fact staying true.
fn cmp_ignoring_ascii_case(a: &str, b: &str) -> std::cmp::Ordering {
    let mut a = a.bytes().map(|c| c.to_ascii_lowercase());
    let mut b = b.bytes().map(|c| c.to_ascii_lowercase());
    loop {
        match (a.next(), b.next()) {
            (None, None) => return std::cmp::Ordering::Equal,
            (None, Some(_)) => return std::cmp::Ordering::Less,
            (Some(_), None) => return std::cmp::Ordering::Greater,
            (Some(x), Some(y)) if x == y => {}
            (Some(x), Some(y)) => return x.cmp(&y),
        }
    }
}

/// The bit index of `lang`, matched case-insensitively.
pub fn index_of(lang: &str) -> Option<usize> {
    rank_of(lang).ok().and_then(bit_of_rank)
}

#[cfg(test)]
mod tests {
    use super::{index_of, nth_sorted, rank_of, LANGS, MAP_WORDS, SORTED};

    /// The table is lowercase, which is what lets a lookup fold only the
    /// caller's side and still order the same way.
    #[test]
    fn every_language_name_is_lowercase() {
        for lang in LANGS {
            assert_eq!(*lang, lang.to_ascii_lowercase(), "{lang}");
        }
    }

    /// A lookup ignores case, and does so without a copy.
    #[test]
    fn a_lookup_ignores_case() {
        for spelling in ["zh-tw", "ZH-TW", "Zh-Tw"] {
            assert_eq!(rank_of(spelling), rank_of("zh-tw"), "{spelling}");
            assert_eq!(index_of(spelling), index_of("zh-tw"), "{spelling}");
        }
    }

    /// A tag that is not there lands where it would be inserted, which is
    /// what the outward walk in `has_lang` starts from.
    #[test]
    fn a_missing_tag_reports_its_insertion_point() {
        let at = rank_of("en-gb").expect_err("not in the table");
        let before = nth_sorted(at.saturating_sub(1)).expect("a neighbour");
        assert!(before <= "en-gb", "{before} should sort before en-gb");
        if let Some(after) = nth_sorted(at) {
            assert!(after >= "en-gb", "{after} should sort after en-gb");
        }
    }

    /// Bit order is fontconfig's declaration order, and it is not sorted.
    /// `bm` really does come before `be`, which is the cheapest way to tell
    /// the two orders apart -- and the thing `fc-list` output shows directly.
    #[test]
    fn bit_order_is_declaration_order_not_alphabetical() {
        let bm = index_of("bm").expect("bm");
        let be = index_of("be").expect("be");
        assert!(bm < be, "bm at {bm}, be at {be}");
        assert!(LANGS.windows(2).any(|w| w[0] > w[1]), "LANGS must not be sorted");
    }

    #[test]
    fn the_sorted_view_is_sorted_and_is_a_permutation() {
        assert_eq!(SORTED.len(), LANGS.len());
        let names: Vec<&str> = SORTED.iter().map(|b| LANGS[*b as usize]).collect();
        assert!(names.windows(2).all(|w| w[0] < w[1]), "SORTED is not sorted");
        let mut bits: Vec<u16> = SORTED.to_vec();
        bits.sort_unstable();
        bits.dedup();
        assert_eq!(bits.len(), LANGS.len(), "SORTED must cover every bit once");
    }

    #[test]
    fn lookup_round_trips_through_both_orders() {
        for (bit, lang) in LANGS.iter().enumerate() {
            assert_eq!(index_of(lang), Some(bit), "{lang}");
        }
        for rank in 0..SORTED.len() {
            let name = nth_sorted(rank).expect("in range");
            assert_eq!(rank_of(name), Ok(rank), "{name}");
        }
    }

    #[test]
    fn well_known_languages_are_present() {
        for lang in ["en", "de", "fr", "ru", "ja", "ko", "ar", "fa", "hi", "th"] {
            assert!(index_of(lang).is_some(), "{lang} missing");
        }
        assert_eq!(index_of("EN"), index_of("en"));
        assert_eq!(index_of("not-a-language"), None);
    }

    #[test]
    fn the_bitmap_is_wide_enough_for_every_language() {
        assert_eq!(MAP_WORDS, LANGS.len().div_ceil(32));
        assert!(LANGS.len() <= MAP_WORDS * 32);
    }

    #[test]
    fn names_are_lowercase_and_use_hyphens() {
        for lang in LANGS {
            assert_eq!(lang, lang.to_lowercase(), "{lang}");
            assert!(!lang.contains('_'), "{lang}");
        }
    }
}
