//! What language a `name` record is written in.
//!
//! A name record identifies its language by a platform-specific number: a
//! Windows LCID, or one of Apple's own codes. Neither is a language tag, and
//! neither is derivable -- fontconfig carries a table, and so does this.
//!
//! Without it a font's localized names cannot be labelled, and fontconfig
//! labels them: a CJK font lists its family in a dozen languages, each tagged.
//!
//! Generated by `tools/gen_name_langs.py` from fontconfig's `fcFtLanguage`
//! and FreeType's `ttnameid.h`: 331 entries.

/// Platform, language id, and the tag fontconfig gives it. Sorted, so a
/// lookup is a binary search.
#[rustfmt::skip]
static LANGUAGES: [(u16, u16, &str); 331] = [
    (1,0x0000,"en"), (1,0x0001,"fr"), (1,0x0002,"de"),
    (1,0x0003,"it"), (1,0x0004,"nl"), (1,0x0005,"sv"),
    (1,0x0006,"es"), (1,0x0007,"da"), (1,0x0008,"pt"),
    (1,0x0009,"no"), (1,0x000a,"he"), (1,0x000b,"ja"),
    (1,0x000c,"ar"), (1,0x000d,"fi"), (1,0x000e,"el"),
    (1,0x000f,"is"), (1,0x0010,"mt"), (1,0x0011,"tr"),
    (1,0x0012,"hr"), (1,0x0013,"zh-tw"), (1,0x0014,"ur"),
    (1,0x0015,"hi"), (1,0x0016,"th"), (1,0x0017,"ko"),
    (1,0x0018,"lt"), (1,0x0019,"pl"), (1,0x001a,"hu"),
    (1,0x001b,"et"), (1,0x001c,"lv"), (1,0x001e,"fo"),
    (1,0x001f,"fa"), (1,0x0020,"ru"), (1,0x0021,"zh-cn"),
    (1,0x0022,"nl"), (1,0x0023,"ga"), (1,0x0024,"sq"),
    (1,0x0025,"ro"), (1,0x0026,"cs"), (1,0x0027,"sk"),
    (1,0x0028,"sl"), (1,0x0029,"yi"), (1,0x002a,"sr"),
    (1,0x002b,"mk"), (1,0x002c,"bg"), (1,0x002d,"uk"),
    (1,0x002e,"be"), (1,0x002f,"uz"), (1,0x0030,"kk"),
    (1,0x0031,"az"), (1,0x0032,"ar"), (1,0x0033,"hy"),
    (1,0x0034,"ka"), (1,0x0035,"mo"), (1,0x0036,"ky"),
    (1,0x0037,"tg"), (1,0x0038,"tk"), (1,0x0039,"mn"),
    (1,0x003a,"mn"), (1,0x003b,"ps"), (1,0x003c,"ku"),
    (1,0x003d,"ks"), (1,0x003e,"sd"), (1,0x003f,"bo"),
    (1,0x0040,"ne"), (1,0x0041,"sa"), (1,0x0042,"mr"),
    (1,0x0043,"bn"), (1,0x0044,"as"), (1,0x0045,"gu"),
    (1,0x0046,"pa"), (1,0x0047,"or"), (1,0x0048,"ml"),
    (1,0x0049,"kn"), (1,0x004a,"ta"), (1,0x004b,"te"),
    (1,0x004c,"si"), (1,0x004d,"my"), (1,0x004e,"km"),
    (1,0x004f,"lo"), (1,0x0050,"vi"), (1,0x0051,"id"),
    (1,0x0052,"tl"), (1,0x0053,"ms"), (1,0x0054,"ms"),
    (1,0x0055,"am"), (1,0x0056,"ti"), (1,0x0057,"om"),
    (1,0x0058,"so"), (1,0x0059,"sw"), (1,0x005a,"rw"),
    (1,0x005b,"rn"), (1,0x005c,"ny"), (1,0x005d,"mg"),
    (1,0x005e,"eo"), (1,0x0080,"cy"), (1,0x0081,"eu"),
    (1,0x0082,"ca"), (1,0x0083,"la"), (1,0x0084,"qu"),
    (1,0x0085,"gn"), (1,0x0086,"ay"), (1,0x0087,"tt"),
    (1,0x0088,"ug"), (1,0x0089,"dz"), (1,0x008a,"jw"),
    (1,0x008b,"su"), (1,0x008c,"gl"), (1,0x008d,"af"),
    (1,0x008e,"br"), (1,0x008f,"iu"), (1,0x0090,"gd"),
    (1,0x0091,"gv"), (1,0x0092,"ga"), (1,0x0093,"to"),
    (1,0x0094,"el"), (1,0x0095,"ik"), (1,0x0096,"az"),
    (3,0x0001,"ar"), (3,0x0004,"zh"), (3,0x0009,"en"),
    (3,0x0401,"ar"), (3,0x0402,"bg"), (3,0x0403,"ca"),
    (3,0x0404,"zh-tw"), (3,0x0405,"cs"), (3,0x0406,"da"),
    (3,0x0407,"de"), (3,0x0408,"el"), (3,0x0409,"en"),
    (3,0x040a,"es"), (3,0x040b,"fi"), (3,0x040c,"fr"),
    (3,0x040d,"he"), (3,0x040e,"hu"), (3,0x040f,"is"),
    (3,0x0410,"it"), (3,0x0411,"ja"), (3,0x0412,"ko"),
    (3,0x0413,"nl"), (3,0x0414,"no"), (3,0x0415,"pl"),
    (3,0x0416,"pt"), (3,0x0417,"rm"), (3,0x0418,"ro"),
    (3,0x0419,"ru"), (3,0x041a,"hr"), (3,0x041b,"sk"),
    (3,0x041c,"sq"), (3,0x041d,"sv"), (3,0x041e,"th"),
    (3,0x041f,"tr"), (3,0x0420,"ur"), (3,0x0421,"id"),
    (3,0x0422,"uk"), (3,0x0423,"be"), (3,0x0424,"sl"),
    (3,0x0425,"et"), (3,0x0426,"lv"), (3,0x0427,"lt"),
    (3,0x0428,"tg"), (3,0x0429,"fa"), (3,0x042a,"vi"),
    (3,0x042b,"hy"), (3,0x042c,"az"), (3,0x042d,"eu"),
    (3,0x042e,"wen"), (3,0x042f,"mk"), (3,0x0430,"st"),
    (3,0x0431,"ts"), (3,0x0432,"tn"), (3,0x0433,"ven"),
    (3,0x0434,"xh"), (3,0x0435,"zu"), (3,0x0436,"af"),
    (3,0x0437,"ka"), (3,0x0438,"fo"), (3,0x0439,"hi"),
    (3,0x043a,"mt"), (3,0x043b,"se"), (3,0x043c,"ga"),
    (3,0x043d,"yi"), (3,0x043e,"ms"), (3,0x043f,"kk"),
    (3,0x0440,"ky"), (3,0x0441,"sw"), (3,0x0442,"tk"),
    (3,0x0443,"uz"), (3,0x0444,"tt"), (3,0x0445,"bn"),
    (3,0x0446,"pa"), (3,0x0447,"gu"), (3,0x0448,"or"),
    (3,0x0449,"ta"), (3,0x044a,"te"), (3,0x044b,"kn"),
    (3,0x044c,"ml"), (3,0x044d,"as"), (3,0x044e,"mr"),
    (3,0x044f,"sa"), (3,0x0450,"mn"), (3,0x0451,"bo"),
    (3,0x0452,"cy"), (3,0x0453,"km"), (3,0x0454,"lo"),
    (3,0x0455,"my"), (3,0x0456,"gl"), (3,0x0457,"kok"),
    (3,0x0458,"mni"), (3,0x0459,"sd"), (3,0x045a,"syr"),
    (3,0x045b,"si"), (3,0x045c,"chr"), (3,0x045d,"iu"),
    (3,0x045e,"am"), (3,0x0460,"ks"), (3,0x0461,"ne"),
    (3,0x0462,"fy"), (3,0x0463,"ps"), (3,0x0464,"phi"),
    (3,0x0465,"div"), (3,0x0468,"ha"), (3,0x046a,"yo"),
    (3,0x0470,"ibo"), (3,0x0471,"kau"), (3,0x0472,"om"),
    (3,0x0473,"ti"), (3,0x0474,"gn"), (3,0x0475,"haw"),
    (3,0x0476,"la"), (3,0x0477,"so"), (3,0x0479,"pap"),
    (3,0x0481,"mi"), (3,0x0801,"ar"), (3,0x0804,"zh-cn"),
    (3,0x0807,"de"), (3,0x0809,"en"), (3,0x080a,"es"),
    (3,0x080c,"fr"), (3,0x0810,"it"), (3,0x0812,"ko"),
    (3,0x0813,"nl"), (3,0x0814,"nn"), (3,0x0816,"pt"),
    (3,0x0818,"mo"), (3,0x0819,"ru"), (3,0x081a,"sr"),
    (3,0x081d,"sv"), (3,0x0820,"ur"), (3,0x0827,"lt"),
    (3,0x082c,"az"), (3,0x083c,"gd"), (3,0x083e,"ms"),
    (3,0x0843,"uz"), (3,0x0845,"bn"), (3,0x0846,"ar"),
    (3,0x0850,"mn"), (3,0x0851,"bo"), (3,0x0860,"ks"),
    (3,0x0861,"ne"), (3,0x0873,"ti"), (3,0x0c01,"ar"),
    (3,0x0c04,"zh-hk"), (3,0x0c07,"de"), (3,0x0c09,"en"),
    (3,0x0c0a,"es"), (3,0x0c0c,"fr"), (3,0x0c1a,"sr"),
    (3,0x1001,"ar"), (3,0x1004,"zh-sg"), (3,0x1007,"de"),
    (3,0x1009,"en"), (3,0x100a,"es"), (3,0x100c,"fr"),
    (3,0x1401,"ar"), (3,0x1404,"zh-mo"), (3,0x1407,"de"),
    (3,0x1409,"en"), (3,0x140a,"es"), (3,0x140c,"fr"),
    (3,0x141a,"bs"), (3,0x1801,"ar"), (3,0x1809,"en"),
    (3,0x180a,"es"), (3,0x180c,"fr"), (3,0x1c01,"ar"),
    (3,0x1c09,"en"), (3,0x1c0a,"es"), (3,0x1c0c,"fr"),
    (3,0x2001,"ar"), (3,0x2009,"en"), (3,0x200a,"es"),
    (3,0x200c,"fr"), (3,0x2401,"ar"), (3,0x2409,"en"),
    (3,0x240a,"es"), (3,0x240c,"fr"), (3,0x2801,"ar"),
    (3,0x2809,"en"), (3,0x280a,"es"), (3,0x280c,"fr"),
    (3,0x2c01,"ar"), (3,0x2c09,"en"), (3,0x2c0a,"es"),
    (3,0x2c0c,"fr"), (3,0x3001,"ar"), (3,0x3009,"en"),
    (3,0x300a,"es"), (3,0x300c,"fr"), (3,0x3401,"ar"),
    (3,0x3409,"en"), (3,0x340a,"es"), (3,0x340c,"fr"),
    (3,0x3801,"ar"), (3,0x380a,"es"), (3,0x380c,"fr"),
    (3,0x3c01,"ar"), (3,0x3c09,"en"), (3,0x3c0a,"es"),
    (3,0x3c0c,"fr"), (3,0x4001,"ar"), (3,0x4009,"en"),
    (3,0x400a,"es"), (3,0x4409,"en"), (3,0x440a,"es"),
    (3,0x4809,"en"), (3,0x480a,"es"), (3,0x4c0a,"es"),
    (3,0x500a,"es"), (3,0x540a,"es"), (3,0xe40a,"es"),
    (3,0xe40c,"fr"),
];

/// The language tag for a name record, or `None` if the id is unknown.
///
/// The Unicode platform carries no language of its own; fontconfig treats
/// those records as English.
pub fn tag(platform: u16, language: u16) -> Option<&'static str> {
    if platform == 0 {
        return Some("en");
    }
    LANGUAGES
        .binary_search_by_key(&(platform, language), |(p, l, _)| (*p, *l))
        .ok()
        .map(|index| LANGUAGES[index].2)
}

#[cfg(test)]
mod tests {
    use super::{tag, LANGUAGES};

    #[test]
    fn the_table_is_sorted_for_binary_search() {
        for pair in LANGUAGES.windows(2) {
            assert!(
                (pair[0].0, pair[0].1) < (pair[1].0, pair[1].1),
                "{:?} then {:?}",
                pair[0],
                pair[1]
            );
        }
    }

    #[test]
    fn the_common_english_ids_resolve() {
        assert_eq!(tag(3, 0x0409), Some("en")); // Windows, English (US)
        assert_eq!(tag(1, 0), Some("en")); // Macintosh, English
        assert_eq!(tag(0, 0), Some("en")); // Unicode platform
        assert_eq!(tag(0, 12345), Some("en")); // ...whatever the id says
    }

    /// Regional variants are distinct ids that fontconfig maps to distinct
    /// tags, which is why a single "en" mapping would not do.
    #[test]
    fn regional_variants_are_distinguished() {
        assert_eq!(tag(3, 0x0809), Some("en")); // English (UK)
        assert_eq!(tag(3, 0x0804), Some("zh-cn"));
        assert_eq!(tag(3, 0x0404), Some("zh-tw"));
        assert_ne!(tag(3, 0x0804), tag(3, 0x0404));
    }

    #[test]
    fn an_unknown_id_is_not_guessed_at() {
        assert_eq!(tag(3, 0xfffe), None);
        assert_eq!(tag(9, 0), None);
    }
}
